# Generated by Django 3.1.1 on 2020-10-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timetemp',
            new_name='timestamp',
        ),
    ]
